## Series
(1D Datastructure in Pandas )

In [50]:
import numpy as np
import pandas as pd

In [3]:
x = [3,4,5,6,7,8]   #series mai used anything dic,tupples,list
S1 = pd.Series(x)  # (x,index=['a','b,'c','d']) #index change karne ke liye
print(S1)

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64

In [4]:
print(type(S1))  
print(S1[0])

<class 'pandas.core.series.Series'>
3

In [5]:
#series mai used anything dic,tupples,list
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
dic = {'a': 10,'b':20,'c':20}

In [6]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(data = my_data,index = labels)  # (x,index=['a','b,'c','d']) #index change karne ke liye

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int32

In [9]:
pd.Series(dic)

a    10
b    20
c    20
dtype: int64

## DataFrame
(2D Datastructure in Pandas0

In [51]:
# Dataframe by using dictionary
dic = {"Name": ['python','c','c++','java'],"rank" : [1,4,3,2]}
var1 = pd.DataFrame(dic) #(dic,columns=["rank"]) #column get karna 
print(var1)

     Name  rank
0  python     1
1       c     4
2     c++     3
3    java     2

In [52]:
print(var1["Name"][2])

c++

In [53]:
print(var1["Name"])

0    python
1         c
2       c++
3      java
Name: Name, dtype: object

In [13]:
# DataFrame Using Numpy
from numpy.random import randn
np.random.seed(101)

In [14]:
# You can also use df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df = pd.DataFrame(randn(5,4),index= ['A','B','C','D', 'E'],columns=['W', 'X','Y','Z'])
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Selection and Indexing

In [15]:
# Extract one column then become Series
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [16]:
type(df['W'])

pandas.core.series.Series

In [17]:
type(df)

pandas.core.frame.DataFrame

In [18]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [19]:
# Creating a new column
df['new'] = df['W'] + df['Y']
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [20]:
# Removing Column
df.drop('new',axis=1,inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [21]:
# Remove rows
df.drop('E',axis=0,inplace=True)
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [22]:
# Selecting Row
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [23]:
# Select based on of position instead of label 
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [24]:
# Selecting subset of rows and columns
df.loc['B','Y']

-0.8480769834036315

In [25]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

In [26]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True

In [27]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057

In [28]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057

In [29]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
Name: Y, dtype: float64

In [30]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [32]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057

In [41]:
newindex = ['AP','UK','UP','MP']

In [42]:
df['States'] = newindex

In [43]:
df.set_index('States')

               W         X         Y         Z
States
AP      2.706850  0.628133  0.907969  0.503826
UK      0.651118 -0.319318 -0.848077  0.605965
UP     -2.018168  0.740122  0.528813 -0.589001
MP      0.188695 -0.758872 -0.933237  0.955057

In [44]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     AP
B  0.651118 -0.319318 -0.848077  0.605965     UK
C -2.018168  0.740122  0.528813 -0.589001     UP
D  0.188695 -0.758872 -0.933237  0.955057     MP

In [45]:
# to save use inplace
df.set_index('States',inplace=True)

In [46]:
df

               W         X         Y         Z
States
AP      2.706850  0.628133  0.907969  0.503826
UK      0.651118 -0.319318 -0.848077  0.605965
UP     -2.018168  0.740122  0.528813 -0.589001
MP      0.188695 -0.758872 -0.933237  0.955057